### ISSUE TITLE
Feat: SetImage onFinished success bool to catch errors

### ISSUE THREAD

**Issue by FrozenAlex** [RedBrumbler/Quest-BSML#103]
To have some sort of way to know if loading an image failed I need a success boolean from onFinished callback

The code in question
https://github.com/RedBrumbler/Quest-BSML/commit/498225ded21d3db4c1e8e6f9d6d45657fbb49197#diff-69c070bacc4b2ff0741daaa1a83e9e9760268a95913f9a4689ce77a0f5249734R301

**Comment by RedBrumbler** [comment]
can be closed when #123 is merged

**Comment by RedBrumbler** [comment]
released in [v0.3.0](https://github.com/RedBrumbler/Quest-BSML/releases/tag/v0.3.0)
